name: Simo Sniper - Global Sports
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Sniping Links
        run: |
          echo '{"en_sport": [' > links.json
          echo '{"name": "Paramount+ HD", "url": "https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8", "logo": "https://upload.wikimedia.org/wikipedia/commons/a/a5/Paramount_Plus.svg"},' >> links.json
          echo '{"name": "EuroSport 1", "url": "https://index.iptv.ovh/eurosport1.m3u8", "logo": "https://upload.wikimedia.org/wikipedia/commons/b/b3/Eurosport_logo.svg"}' >> links.json
          echo '], "en_news": []}' >> links.json

      - name: Commit and Push
        run: |
          git config --global user.name "Simo-Sniper"
          git config --global user.email "simo@mytvpro.com"
          git add links.json
          git commit -m "Simo Sniper: Global Sports Updated" || exit 0
          git push
